create table if not exists mail_outbox (
  id bigint generated by default as identity primary key,
  audience varchar(40) not null,
  mail_type varchar(80) not null,
  recipient varchar(180) not null,
  subject varchar(255) not null,
  body text not null,
  status varchar(40) not null default 'pending',
  error_message text,
  created_at timestamp not null default current_timestamp,
  sent_at timestamp
);

create index if not exists idx_mail_outbox_recipient_type on mail_outbox (recipient, mail_type);

create table if not exists password_reset_tokens (
  id bigint generated by default as identity primary key,
  email varchar(180) not null,
  token varchar(120) not null unique,
  expires_at timestamp not null,
  used_at timestamp,
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_password_reset_tokens_email on password_reset_tokens (email);
