create table if not exists event_outbox (
  id bigint generated by default as identity primary key,
  event_type varchar(80) not null,
  aggregate_type varchar(80) not null,
  aggregate_id bigint not null,
  payload text not null default '{}',
  status varchar(30) not null default 'pending',
  attempts int not null default 0,
  error_message text,
  next_attempt_at timestamp,
  sent_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index if not exists idx_event_outbox_status_created on event_outbox (status, created_at);
create index if not exists idx_event_outbox_type_aggregate on event_outbox (event_type, aggregate_type, aggregate_id);

create table if not exists event_consumptions (
  id bigint generated by default as identity primary key,
  event_id bigint not null,
  consumer_name varchar(120) not null,
  consumed_at timestamp not null default current_timestamp,
  unique (event_id, consumer_name)
);
