create table albums (
  id bigint generated by default as identity primary key,
  title varchar(200) not null,
  slug varchar(160) not null,
  description text,
  cover_url varchar(1000),
  sort_order integer not null default 0,
  is_public boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint uk_albums_slug unique (slug)
);

create table album_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null,
  file_id bigint,
  image_url varchar(1000) not null,
  title varchar(200),
  description text,
  sort_order integer not null default 0,
  is_public boolean not null default true,
  taken_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint fk_album_photos_album foreign key (album_id) references albums(id) on delete cascade,
  constraint fk_album_photos_file foreign key (file_id) references files(id) on delete set null
);

create index idx_albums_public_sort on albums (is_public, sort_order, created_at desc, id desc);
create index idx_album_photos_album_sort on album_photos (album_id, is_public, sort_order, created_at, id);
