create table if not exists guestbook_messages (
  id bigint generated by default as identity primary key,
  nickname varchar(64) not null,
  email varchar(255),
  content text not null,
  status varchar(32) not null default 'pending',
  pinned boolean not null default false,
  ip varchar(64),
  user_agent text,
  admin_note text,
  deleted boolean not null default false,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create index if not exists idx_guestbook_messages_status_created
  on guestbook_messages(status, created_at desc, id desc);

create index if not exists idx_guestbook_messages_pinned_created
  on guestbook_messages(pinned desc, created_at desc, id desc);

create index if not exists idx_guestbook_messages_deleted_created
  on guestbook_messages(deleted, created_at desc, id desc);
