create table if not exists categories (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  slug varchar(160) not null unique,
  description varchar(500) not null default '',
  sort_order integer not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists tags (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  slug varchar(160) not null unique,
  description varchar(500) not null default '',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

create table if not exists articles (
  id bigint generated by default as identity primary key,
  slug varchar(180) not null unique,
  title varchar(240) not null,
  summary varchar(1000) not null default '',
  cover_url varchar(500),
  content_markdown clob not null,
  content_html clob not null,
  content_text clob not null,
  status varchar(30) not null,
  category_id bigint,
  is_top boolean not null default false,
  is_essence boolean not null default false,
  is_outdated boolean not null default false,
  view_count bigint not null default 0,
  comment_count bigint not null default 0,
  location varchar(120),
  published_at timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint fk_articles_category foreign key (category_id) references categories(id)
);

create table if not exists article_tags (
  article_id bigint not null,
  tag_id bigint not null,
  primary key (article_id, tag_id),
  constraint fk_article_tags_article foreign key (article_id) references articles(id) on delete cascade,
  constraint fk_article_tags_tag foreign key (tag_id) references tags(id) on delete cascade
);

create table if not exists menus (
  id bigint generated by default as identity primary key,
  type varchar(40) not null,
  parent_id bigint,
  title varchar(120) not null,
  url varchar(500) not null,
  icon varchar(120) not null default '',
  sort_order integer not null default 0
);

insert into categories (name, slug, description, sort_order)
select '默认分类', 'default', 'ZBlog2 默认文章分类', 1
where not exists (select 1 from categories where slug = 'default');

insert into tags (name, slug, description)
select 'ZBlog2', 'zblog2', 'ZBlog2 项目记录'
where not exists (select 1 from tags where slug = 'zblog2');

insert into articles (
  slug, title, summary, content_markdown, content_html, content_text, status,
  category_id, is_top, is_essence, published_at
)
select
  'hello-zblog2',
  'Hello ZBlog2',
  'ZBlog2 Java 后端文章系统已经启动。',
  '# Hello ZBlog2 这是一篇由 Phase 3 baseline 创建的示例文章。',
  '<h1>Hello ZBlog2</h1><p>这是一篇由 Phase 3 baseline 创建的示例文章。</p>',
  'Hello ZBlog2 这是一篇由 Phase 3 baseline 创建的示例文章。',
  'PUBLISHED',
  (select id from categories where slug = 'default'),
  true,
  true,
  current_timestamp
where not exists (select 1 from articles where slug = 'hello-zblog2');

insert into article_tags (article_id, tag_id)
select a.id, t.id
from articles a, tags t
where a.slug = 'hello-zblog2'
  and t.slug = 'zblog2'
  and not exists (
    select 1 from article_tags at where at.article_id = a.id and at.tag_id = t.id
  );

insert into menus (type, title, url, icon, sort_order)
select 'navigation', '首页', '/', 'ri-home-line', 1
where not exists (select 1 from menus where type = 'navigation' and url = '/');

insert into menus (type, title, url, icon, sort_order)
select 'navigation', '归档', '/archive', 'ri-archive-line', 2
where not exists (select 1 from menus where type = 'navigation' and url = '/archive');

insert into menus (type, title, url, icon, sort_order)
select 'footer', '分类', '/categories', 'ri-folder-line', 1
where not exists (select 1 from menus where type = 'footer' and url = '/categories');
