-- P4 interaction discovery additive schema changes.

-- Feedback ticket access, ownership, status timestamps, and timeline support.
alter table feedbacks add column if not exists access_token varchar(120);
alter table feedbacks add column if not exists user_id bigint;
alter table feedbacks add column if not exists updated_at timestamp not null default current_timestamp;
alter table feedbacks add column if not exists resolved_at timestamp;
alter table feedbacks add column if not exists closed_at timestamp;
alter table feedbacks add column if not exists last_user_reply_at timestamp;
alter table feedbacks add column if not exists last_admin_reply_at timestamp;

update feedbacks set status = upper(status)
where status in ('pending', 'resolved', 'closed');

alter table feedbacks alter column status set default 'PENDING';

create unique index if not exists uk_feedbacks_access_token on feedbacks(access_token);
create index if not exists idx_feedbacks_user_status on feedbacks(user_id, status);
create index if not exists idx_feedbacks_status_updated on feedbacks(status, updated_at);

create table if not exists feedback_messages (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null,
  actor_type varchar(40) not null,
  actor_user_id bigint,
  message_type varchar(40) not null,
  content text not null default '',
  attachments_json text not null default '[]',
  from_status varchar(40),
  to_status varchar(40),
  created_at timestamp not null default current_timestamp,
  constraint fk_feedback_messages_feedback foreign key (feedback_id) references feedbacks(id)
);

create index if not exists idx_feedback_messages_feedback_created on feedback_messages(feedback_id, created_at, id);

-- Subscriber lifecycle and delivery diagnostics.
alter table subscribers add column if not exists status varchar(40);
alter table subscribers add column if not exists confirmation_token varchar(120);
alter table subscribers add column if not exists confirmed_at timestamp;
alter table subscribers add column if not exists unsubscribed_at timestamp;
alter table subscribers add column if not exists bounced_at timestamp;
alter table subscribers add column if not exists failure_count int not null default 0;
alter table subscribers add column if not exists last_delivery_status varchar(40);
alter table subscribers add column if not exists last_delivery_error text;
alter table subscribers add column if not exists last_delivery_at timestamp;

update subscribers
set status = case when active = true then 'ACTIVE' else 'UNSUBSCRIBED' end
where status is null;

alter table subscribers alter column status set default 'PENDING';
alter table subscribers alter column status set not null;

create unique index if not exists uk_subscribers_confirmation_token on subscribers(confirmation_token);
create index if not exists idx_subscribers_status on subscribers(status);

-- Article copyright metadata.
alter table articles add column if not exists copyright_type varchar(40) not null default 'ORIGINAL';
alter table articles add column if not exists source_url varchar(1000) not null default '';
alter table articles add column if not exists source_title varchar(500) not null default '';
alter table articles add column if not exists copyright_license varchar(120) not null default '';

create index if not exists idx_articles_copyright_type on articles(copyright_type);

-- Feedback cleanup scheduled job seed. Handler implementation is added in P4 code.
insert into scheduled_jobs (name, handler_name, cron_expression, parameters, enabled, description)
select 'Feedback cleanup', 'feedback-cleanup', '0 30 3 * * ?', '{"retentionDays":90}', true,
  'Delete resolved/closed feedback tickets older than the retention window.'
where not exists (
  select 1 from scheduled_jobs where handler_name = 'feedback-cleanup'
);

