create table if not exists comments (
  id bigint generated by default as identity primary key,
  target_type varchar(40) not null,
  target_key varchar(180) not null,
  parent_id bigint,
  content text not null,
  status integer not null default 1,
  is_deleted boolean not null default false,
  nickname varchar(120) not null default 'Guest',
  email varchar(180) not null default '',
  website varchar(500),
  avatar varchar(500) not null default '',
  location varchar(120),
  browser varchar(120),
  os varchar(120),
  created_at timestamp not null default current_timestamp,
  deleted_at timestamp,
  constraint fk_comments_parent foreign key (parent_id) references comments(id)
);

create table if not exists friend_types (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  sort_order integer not null default 0,
  is_visible boolean not null default true
);

create table if not exists friends (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  url varchar(500) not null,
  description varchar(1000) not null default '',
  avatar varchar(500) not null default '',
  screenshot varchar(500) not null default '',
  sort_order integer not null default 0,
  type_id bigint,
  is_invalid boolean not null default false,
  is_pending boolean not null default false,
  rss_url varchar(500) not null default '',
  accessible integer not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint fk_friends_type foreign key (type_id) references friend_types(id)
);

create table if not exists files (
  id bigint generated by default as identity primary key,
  filename varchar(255) not null,
  original_name varchar(255) not null,
  file_url varchar(500) not null,
  file_type varchar(120) not null default '',
  file_size bigint not null default 0,
  upload_type varchar(80) not null default '',
  status integer not null default 0,
  upload_time timestamp not null default current_timestamp,
  deleted_at timestamp
);

create table if not exists settings (
  id bigint generated by default as identity primary key,
  group_name varchar(80) not null,
  key_name varchar(160) not null,
  value_text text not null,
  updated_at timestamp not null default current_timestamp,
  constraint uq_settings_group_key unique (group_name, key_name)
);

insert into friend_types (name, sort_order, is_visible)
select '友情链接', 1, true
where not exists (select 1 from friend_types where name = '友情链接');

insert into settings (group_name, key_name, value_text)
select 'basic', 'site_name', 'ZBlog'
where not exists (select 1 from settings where group_name = 'basic' and key_name = 'site_name');

insert into settings (group_name, key_name, value_text)
select 'basic', 'site_description', '一个正在构建中的现代博客'
where not exists (select 1 from settings where group_name = 'basic' and key_name = 'site_description');

insert into settings (group_name, key_name, value_text)
select 'blog', 'moments_size', '30'
where not exists (select 1 from settings where group_name = 'blog' and key_name = 'moments_size');

insert into settings (group_name, key_name, value_text)
select 'upload', 'max_size_mb', '10'
where not exists (select 1 from settings where group_name = 'upload' and key_name = 'max_size_mb');
