create table if not exists moments (
  id bigint generated by default as identity primary key,
  content_json text not null,
  is_publish boolean not null default true,
  publish_time timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);
