create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(180) not null unique,
  password_hash varchar(255),
  nickname varchar(80) not null,
  avatar varchar(500) not null default '',
  badge varchar(80),
  website varchar(500),
  role varchar(40) not null default 'user',
  is_enabled boolean not null default true,
  deleted_at timestamp,
  last_login timestamp,
  github_id varchar(120) not null default '',
  google_id varchar(120) not null default '',
  qq_id varchar(120) not null default '',
  microsoft_id varchar(120) not null default '',
  feishu_open_id varchar(120) not null default '',
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp
);

insert into users (email, password_hash, nickname, role, is_enabled)
select 'admin', '{noop}admin123456', 'admin', 'super_admin', true
where not exists (select 1 from users where email = 'admin');
