create table if not exists feedbacks (
  id bigint generated by default as identity primary key,
  ticket_no varchar(40) not null unique,
  report_url varchar(1000) not null default '',
  report_type varchar(40) not null,
  form_content text not null,
  email varchar(180) not null default '',
  status varchar(40) not null default 'pending',
  admin_reply text not null default '',
  reply_time timestamp,
  user_agent varchar(1000) not null default '',
  ip varchar(80) not null default '',
  feedback_time timestamp not null default current_timestamp,
  deleted_at timestamp
);

create table if not exists subscribers (
  id bigint generated by default as identity primary key,
  email varchar(180) not null unique,
  unsubscribe_token varchar(80) not null unique,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  deleted_at timestamp
);

create table if not exists rss_feed_articles (
  id bigint generated by default as identity primary key,
  friend_id bigint,
  title varchar(500) not null,
  link varchar(1000) not null,
  description text not null default '',
  published_at timestamp,
  is_read boolean not null default false,
  created_at timestamp not null default current_timestamp,
  constraint fk_rss_feed_articles_friend foreign key (friend_id) references friends(id)
);

insert into subscribers (email, unsubscribe_token, active)
select 'reader@example.com', 'seed-reader-token', true
where not exists (select 1 from subscribers where email = 'reader@example.com');

insert into friends (name, url, description, avatar, sort_order, type_id, is_pending, rss_url, accessible)
select 'ZBlog Reference', 'https://example.com', 'Reference RSS source', '', 10, ft.id, true, 'https://example.com/rss.xml', 1
from friend_types ft
where ft.name = '友情链接'
  and not exists (select 1 from friends where name = 'ZBlog Reference');

insert into rss_feed_articles (friend_id, title, link, description, published_at, is_read)
select f.id, 'Reference RSS Article', 'https://example.com/rss-article', 'Seed RSS article for admin feed verification.', current_timestamp, false
from friends f
where f.name = 'ZBlog Reference'
  and not exists (select 1 from rss_feed_articles where link = 'https://example.com/rss-article');
