create table if not exists visit_events (
  id bigint generated by default as identity primary key,
  visitor_id varchar(120) not null,
  event_type varchar(40) not null,
  url varchar(1000) not null default '',
  hostname varchar(255) not null default '',
  title varchar(500) not null default '',
  referrer varchar(1000) not null default '',
  language varchar(80) not null default '',
  screen varchar(80) not null default '',
  article_id bigint,
  event_name varchar(120) not null default '',
  event_data text not null default '{}',
  duration_seconds integer,
  ip varchar(80) not null default '',
  user_agent varchar(1000) not null default '',
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_visit_events_created_at on visit_events (created_at);
create index if not exists idx_visit_events_type_created_at on visit_events (event_type, created_at);
create index if not exists idx_visit_events_visitor_id on visit_events (visitor_id);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  type varchar(80) not null,
  title varchar(240) not null,
  content text not null default '',
  link varchar(1000) not null default '',
  data text not null default '{}',
  target_id bigint,
  is_read boolean not null default false,
  read_at timestamp,
  sender varchar(120),
  created_at timestamp not null default current_timestamp
);

create index if not exists idx_notifications_read_created_at on notifications (is_read, created_at);
